version: "3.7"
services:

  #Laravel App
  app:
    build:
      args:
        user: notmii
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: test-app
    container_name: test-webapp
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./app:/var/www
